### ISSUE TITLE
Inclusion/Exclusion explanation

### ISSUE THREAD

**Issue by Vimos** [sohuren/DPL_release#1]
In the data and code, I find the `inclusion/exclusion` split, can you offer some information about the meaning of the term?

**Comment by sohuren** [comment]
We originally do experiment on the clinical trial, e.g, https://clinicaltrials.gov/ct2/show/NCT03922373?rank=1

Which has the inclusion and exclusion criteria, if we just do the experiment on pubmed, then we can ignore those terms.

**Comment by Vimos** [comment]
Got it! Thanks!
